Error: 200324 11:14:33Error en la conexion a org.postgresql.Driver
	 org.postgresql.util.PSQLException: FATAL: la autentificaci?n password fall? para el usuario ?at.pos?
		org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:398)
		org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:173)
		org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
		org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
		org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
		org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
		org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
		org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
		org.postgresql.Driver.makeConnection(Driver.java:410)
		org.postgresql.Driver.connect(Driver.java:280)
		java.sql.DriverManager.getConnection(Unknown Source)
		java.sql.DriverManager.getConnection(Unknown Source)
		com.pos.db.DataBase.conectarDB(DataBase.java:96)
		com.pos.db.DataBase.<init>(DataBase.java:66)
		com.pos.db.ProcesoImportacion.actualizarProcesoImportacion(ProcesoImportacion.java:132)
		com.pos.apl.SincronizacionGral.run(SincronizacionGral.java:75)

Error: 200324 11:14:34Error en la conexion a org.postgresql.Driver
	 org.postgresql.util.PSQLException: FATAL: la autentificaci?n password fall? para el usuario ?at.pos?
		org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:398)
		org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:173)
		org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
		org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
		org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
		org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
		org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
		org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
		org.postgresql.Driver.makeConnection(Driver.java:410)
		org.postgresql.Driver.connect(Driver.java:280)
		java.sql.DriverManager.getConnection(Unknown Source)
		java.sql.DriverManager.getConnection(Unknown Source)
		com.pos.db.DataBase.conectarDB(DataBase.java:96)
		com.pos.db.DataBase.<init>(DataBase.java:66)
		com.pos.db.ProcesoImportacion.actualizarProcesoImportacion(ProcesoImportacion.java:132)
		com.pos.apl.SincronizadorArticulo.run(SincronizadorArticulo.java:125)

Error: 200324 11:14:34Error en la conexion a org.postgresql.Driver
	 org.postgresql.util.PSQLException: FATAL: la autentificaci?n password fall? para el usuario ?at.pos?
		org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:398)
		org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:173)
		org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64)
		org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:136)
		org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29)
		org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21)
		org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31)
		org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
		org.postgresql.Driver.makeConnection(Driver.java:410)
		org.postgresql.Driver.connect(Driver.java:280)
		java.sql.DriverManager.getConnection(Unknown Source)
		java.sql.DriverManager.getConnection(Unknown Source)
		com.pos.db.DataBase.conectarDB(DataBase.java:96)
		com.pos.db.DataBase.<init>(DataBase.java:66)
		com.pos.db.ProcesoExportacion.actualizarProcesoExportacion(ProcesoExportacion.java:181)
		com.pos.apl.Exportador.run(Exportador.java:99)

